### ISSUE TITLE
Filenames incompatible with NTFS and Windows

### ISSUE THREAD

**Issue by vgeddes** [AstromechZA/spiro#4]
Hi Ben :)

I am using a project which depends on Spiro, and the files named in the form `<<<foo>>>` are incompatible with NTFS.

```
Checking connectivity... done.
fatal: cannot create directory at 'devscripts/spiro_templates/template_service/<<<.service_name>>>': No such file or directory
warning: Clone succeeded, but checkout failed.
You can inspect what was checked out with 'git status'
and retry the checkout with 'git checkout -f HEAD'
```

Just thought I'd let you now.

**Comment by astromechza** [comment]
Hey, thats why the spec file itself can define the delimiter characters used: https://github.com/AstromechZA/spiro#overriding-the-template-characters. This is so that you can use `{{{` or `(((` or `@@@` if the filesystem is picky or if you use the characters too much in your template files.

Closing this since its not an issue.

**Comment by vgeddes** [comment]
:+1:
